//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.srLabcoreTAT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srLabcoreTAT.ILabLinkHUSI")]
    public interface ILabLinkHUSI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabLinkHUSI/SetHl7", ReplyAction="http://tempuri.org/ILabLinkHUSI/SetHl7Response")]
        string SetHl7(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabLinkHUSI/GetPDFBase64", ReplyAction="http://tempuri.org/ILabLinkHUSI/GetPDFBase64Response")]
        string GetPDFBase64(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabLinkHUSI/GetPDF", ReplyAction="http://tempuri.org/ILabLinkHUSI/GetPDFResponse")]
        System.IO.Stream GetPDF(string numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILabLinkHUSIChannel : labcoreWS.srLabcoreTAT.ILabLinkHUSI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabLinkHUSIClient : System.ServiceModel.ClientBase<labcoreWS.srLabcoreTAT.ILabLinkHUSI>, labcoreWS.srLabcoreTAT.ILabLinkHUSI {
        
        public LabLinkHUSIClient() {
        }
        
        public LabLinkHUSIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabLinkHUSIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabLinkHUSIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabLinkHUSIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SetHl7(string mensaje) {
            return base.Channel.SetHl7(mensaje);
        }
        
        public string GetPDFBase64(string numero) {
            return base.Channel.GetPDFBase64(numero);
        }
        
        public System.IO.Stream GetPDF(string numero) {
            return base.Channel.GetPDF(numero);
        }
    }
}
