//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.srLabcoreResultados {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srLabcoreResultados.IWSSolicitudes")]
    public interface IWSSolicitudes {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WSSolicitudesIntf-IWSSolicitudes) of message RecResultsRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSSolicitudesIntf-IWSSolicitudes#RecResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        labcoreWS.srLabcoreResultados.RecResultsResponse RecResults(labcoreWS.srLabcoreResultados.RecResultsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WSSolicitudesIntf-IWSSolicitudes) of message RecSolicitudesRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSSolicitudesIntf-IWSSolicitudes#RecSolicitudes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        labcoreWS.srLabcoreResultados.RecSolicitudesResponse RecSolicitudes(labcoreWS.srLabcoreResultados.RecSolicitudesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WSSolicitudesIntf-IWSSolicitudes) of message GetResultPdfRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSSolicitudesIntf-IWSSolicitudes#GetResultPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        labcoreWS.srLabcoreResultados.GetResultPdfResponse GetResultPdf(labcoreWS.srLabcoreResultados.GetResultPdfRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WSSolicitudesIntf-IWSSolicitudes) of message GetHL7MsgRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSSolicitudesIntf-IWSSolicitudes#GetHL7Msg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        labcoreWS.srLabcoreResultados.GetHL7MsgResponse GetHL7Msg(labcoreWS.srLabcoreResultados.GetHL7MsgRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WSSolicitudesIntf-IWSSolicitudes) of message CambioEstadoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSSolicitudesIntf-IWSSolicitudes#CambioEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        labcoreWS.srLabcoreResultados.CambioEstadoResponse CambioEstado(labcoreWS.srLabcoreResultados.CambioEstadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecResults", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class RecResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlRes;
        
        public RecResultsRequest() {
        }
        
        public RecResultsRequest(string xmlRes) {
            this.xmlRes = xmlRes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecResultsResponse", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class RecResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RecResultsResponse() {
        }
        
        public RecResultsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecSolicitudes", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class RecSolicitudesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlSol;
        
        public RecSolicitudesRequest() {
        }
        
        public RecSolicitudesRequest(string xmlSol) {
            this.xmlSol = xmlSol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecSolicitudesResponse", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class RecSolicitudesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RecSolicitudesResponse() {
        }
        
        public RecSolicitudesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResultPdf", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class GetResultPdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string numorden;
        
        public GetResultPdfRequest() {
        }
        
        public GetResultPdfRequest(string numorden) {
            this.numorden = numorden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResultPdfResponse", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class GetResultPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetResultPdfResponse() {
        }
        
        public GetResultPdfResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHL7Msg", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class GetHL7MsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string msg;
        
        public GetHL7MsgRequest() {
        }
        
        public GetHL7MsgRequest(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHL7MsgResponse", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class GetHL7MsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetHL7MsgResponse() {
        }
        
        public GetHL7MsgResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambioEstado", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class CambioEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string msg;
        
        public CambioEstadoRequest() {
        }
        
        public CambioEstadoRequest(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambioEstadoResponse", WrapperNamespace="urn:WSSolicitudesIntf-IWSSolicitudes", IsWrapped=true)]
    public partial class CambioEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CambioEstadoResponse() {
        }
        
        public CambioEstadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSSolicitudesChannel : labcoreWS.srLabcoreResultados.IWSSolicitudes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSolicitudesClient : System.ServiceModel.ClientBase<labcoreWS.srLabcoreResultados.IWSSolicitudes>, labcoreWS.srLabcoreResultados.IWSSolicitudes {
        
        public WSSolicitudesClient() {
        }
        
        public WSSolicitudesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSolicitudesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSolicitudesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSolicitudesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.srLabcoreResultados.RecResultsResponse labcoreWS.srLabcoreResultados.IWSSolicitudes.RecResults(labcoreWS.srLabcoreResultados.RecResultsRequest request) {
            return base.Channel.RecResults(request);
        }
        
        public string RecResults(string xmlRes) {
            labcoreWS.srLabcoreResultados.RecResultsRequest inValue = new labcoreWS.srLabcoreResultados.RecResultsRequest();
            inValue.xmlRes = xmlRes;
            labcoreWS.srLabcoreResultados.RecResultsResponse retVal = ((labcoreWS.srLabcoreResultados.IWSSolicitudes)(this)).RecResults(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.srLabcoreResultados.RecSolicitudesResponse labcoreWS.srLabcoreResultados.IWSSolicitudes.RecSolicitudes(labcoreWS.srLabcoreResultados.RecSolicitudesRequest request) {
            return base.Channel.RecSolicitudes(request);
        }
        
        public string RecSolicitudes(string xmlSol) {
            labcoreWS.srLabcoreResultados.RecSolicitudesRequest inValue = new labcoreWS.srLabcoreResultados.RecSolicitudesRequest();
            inValue.xmlSol = xmlSol;
            labcoreWS.srLabcoreResultados.RecSolicitudesResponse retVal = ((labcoreWS.srLabcoreResultados.IWSSolicitudes)(this)).RecSolicitudes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.srLabcoreResultados.GetResultPdfResponse labcoreWS.srLabcoreResultados.IWSSolicitudes.GetResultPdf(labcoreWS.srLabcoreResultados.GetResultPdfRequest request) {
            return base.Channel.GetResultPdf(request);
        }
        
        public string GetResultPdf(string numorden) {
            labcoreWS.srLabcoreResultados.GetResultPdfRequest inValue = new labcoreWS.srLabcoreResultados.GetResultPdfRequest();
            inValue.numorden = numorden;
            labcoreWS.srLabcoreResultados.GetResultPdfResponse retVal = ((labcoreWS.srLabcoreResultados.IWSSolicitudes)(this)).GetResultPdf(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.srLabcoreResultados.GetHL7MsgResponse labcoreWS.srLabcoreResultados.IWSSolicitudes.GetHL7Msg(labcoreWS.srLabcoreResultados.GetHL7MsgRequest request) {
            return base.Channel.GetHL7Msg(request);
        }
        
        public string GetHL7Msg(string msg) {
            labcoreWS.srLabcoreResultados.GetHL7MsgRequest inValue = new labcoreWS.srLabcoreResultados.GetHL7MsgRequest();
            inValue.msg = msg;
            labcoreWS.srLabcoreResultados.GetHL7MsgResponse retVal = ((labcoreWS.srLabcoreResultados.IWSSolicitudes)(this)).GetHL7Msg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.srLabcoreResultados.CambioEstadoResponse labcoreWS.srLabcoreResultados.IWSSolicitudes.CambioEstado(labcoreWS.srLabcoreResultados.CambioEstadoRequest request) {
            return base.Channel.CambioEstado(request);
        }
        
        public string CambioEstado(string msg) {
            labcoreWS.srLabcoreResultados.CambioEstadoRequest inValue = new labcoreWS.srLabcoreResultados.CambioEstadoRequest();
            inValue.msg = msg;
            labcoreWS.srLabcoreResultados.CambioEstadoResponse retVal = ((labcoreWS.srLabcoreResultados.IWSSolicitudes)(this)).CambioEstado(inValue);
            return retVal.@return;
        }
    }
}
