//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.WSAldea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://habitatclient.service.soapws.core.axesnet.com/", ConfigurationName="WSAldea.ISmsSendSoap")]
    public interface ISmsSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://habitatclient.service.soapws.core.axesnet.com/ISmsSendSoap/smsSendSoapRequ" +
            "est", ReplyAction="http://habitatclient.service.soapws.core.axesnet.com/ISmsSendSoap/smsSendSoapResp" +
            "onse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string smsSendSoap(string username, string password, long country, string mobile, string message, string @operator);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsSendSoapChannel : labcoreWS.WSAldea.ISmsSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSendSoapClient : System.ServiceModel.ClientBase<labcoreWS.WSAldea.ISmsSendSoap>, labcoreWS.WSAldea.ISmsSendSoap {
        
        public SmsSendSoapClient() {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string smsSendSoap(string username, string password, long country, string mobile, string message, string @operator) {
            return base.Channel.smsSendSoap(username, password, country, mobile, message, @operator);
        }
    }
}
