//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINTVTIDESBD;Initial Catalog=SAHI_ASI_DES;User ID=Desarrollo;Password" +
            "=PwdDes;MultipleActiveResultSets=True")]
        public string alterno {
            get {
                return ((string)(this["alterno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TYCHO;Initial Catalog=HSI_PRI;User ID=interface;Password=interface;Mi" +
            "n Pool Size=10;Max Pool Size=800;MultipleActiveResultSets=True;Connect Timeout=6" +
            "0;ConnectRetryCount=3")]
        public string DBConexionXX {
            get {
                return ((string)(this["DBConexionXX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TYCHO;Initial Catalog=HSI_PRI;User ID=interface;Password=interface;Mi" +
            "n Pool Size=10;Max Pool Size=800;MultipleActiveResultSets=True;Connect Timeout=6" +
            "0;ConnectRetryCount=3")]
        public string DBConexion {
            get {
                return ((string)(this["DBConexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TYCHO;Initial Catalog=HSI_PRI;User ID=interface;Password=interface;Mi" +
            "n Pool Size=10;Max Pool Size=800;MultipleActiveResultSets=True;Connect Timeout=6" +
            "0;ConnectRetryCount=3")]
        public string LabcoreDBConXX {
            get {
                return ((string)(this["LabcoreDBConXX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TYCHO;Initial Catalog=HSI_PRI;User ID=interface;Password=interface;Mi" +
            "n Pool Size=10;Max Pool Size=800;MultipleActiveResultSets=True;Connect Timeout=6" +
            "0;ConnectRetryCount=3")]
        public string LabcoreDBCon {
            get {
                return ((string)(this["LabcoreDBCon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TYCHO;Initial Catalog=HSI_PRI;User ID=interface;Password=interface;Mi" +
            "n Pool Size=10;Max Pool Size=800;MultipleActiveResultSets=True;Connect Timeout=6" +
            "0;ConnectRetryCount=3")]
        public string dbProduccion {
            get {
                return ((string)(this["dbProduccion"]));
            }
        }
    }
}
