//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.clienteSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://husi.org/", ConfigurationName="clienteSMS.smsHUSISoap")]
    public interface smsHUSISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/EnviaSMSHUSI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EnviaSMSHUSI(string idDocPac, string _idEspecial, string idsolInter, string paciente, string cama, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/ReenviarSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReenviarSMS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/smsGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string smsGeneral(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS, string asunto, string msgCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/correoGeneralHusi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string correoGeneralHusi(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS, string asunto, string msgCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/smsGeneralHusi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string smsGeneralHusi(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/correoHusi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string correoHusi(string correoOrigen, string correosDestino, string asunto, string msgCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/smsGeneralMobiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string smsGeneralMobiles(string codigoServicio, string nroMobil, string msgSMS);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsHUSISoapChannel : labcoreWS.clienteSMS.smsHUSISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsHUSISoapClient : System.ServiceModel.ClientBase<labcoreWS.clienteSMS.smsHUSISoap>, labcoreWS.clienteSMS.smsHUSISoap {
        
        public smsHUSISoapClient() {
        }
        
        public smsHUSISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsHUSISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsHUSISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsHUSISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EnviaSMSHUSI(string idDocPac, string _idEspecial, string idsolInter, string paciente, string cama, string tipo) {
            return base.Channel.EnviaSMSHUSI(idDocPac, _idEspecial, idsolInter, paciente, cama, tipo);
        }
        
        public string ReenviarSMS() {
            return base.Channel.ReenviarSMS();
        }
        
        public string smsGeneral(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS, string asunto, string msgCorreo) {
            return base.Channel.smsGeneral(idDocPac, servicio, nroServicio, paciente, cama, msgSMS, asunto, msgCorreo);
        }
        
        public string correoGeneralHusi(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS, string asunto, string msgCorreo) {
            return base.Channel.correoGeneralHusi(idDocPac, servicio, nroServicio, paciente, cama, msgSMS, asunto, msgCorreo);
        }
        
        public string smsGeneralHusi(string idDocPac, string servicio, string nroServicio, string paciente, string cama, string msgSMS) {
            return base.Channel.smsGeneralHusi(idDocPac, servicio, nroServicio, paciente, cama, msgSMS);
        }
        
        public string correoHusi(string correoOrigen, string correosDestino, string asunto, string msgCorreo) {
            return base.Channel.correoHusi(correoOrigen, correosDestino, asunto, msgCorreo);
        }
        
        public string smsGeneralMobiles(string codigoServicio, string nroMobil, string msgSMS) {
            return base.Channel.smsGeneralMobiles(codigoServicio, nroMobil, msgSMS);
        }
    }
}
