//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.servicioPruebasLabcore {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://husi.org/", ConfigurationName="servicioPruebasLabcore.wsLabcoreSahiSoap")]
    public interface wsLabcoreSahiSoap {
        
        // CODEGEN: Generating message contract since element name ordenesInput from namespace http://husi.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/ordenes", ReplyAction="*")]
        labcoreWS.servicioPruebasLabcore.ordenesResponse ordenes(labcoreWS.servicioPruebasLabcore.ordenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/ordenes", ReplyAction="*")]
        System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.ordenesResponse> ordenesAsync(labcoreWS.servicioPruebasLabcore.ordenesRequest request);
        
        // CODEGEN: Generating message contract since element name solicitudInput from namespace http://husi.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/solicitudes", ReplyAction="*")]
        labcoreWS.servicioPruebasLabcore.solicitudesResponse solicitudes(labcoreWS.servicioPruebasLabcore.solicitudesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://husi.org/solicitudes", ReplyAction="*")]
        System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.solicitudesResponse> solicitudesAsync(labcoreWS.servicioPruebasLabcore.solicitudesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenes", Namespace="http://husi.org/", Order=0)]
        public labcoreWS.servicioPruebasLabcore.ordenesRequestBody Body;
        
        public ordenesRequest() {
        }
        
        public ordenesRequest(labcoreWS.servicioPruebasLabcore.ordenesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://husi.org/")]
    public partial class ordenesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ordenesInput;
        
        public ordenesRequestBody() {
        }
        
        public ordenesRequestBody(string ordenesInput) {
            this.ordenesInput = ordenesInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenesResponse", Namespace="http://husi.org/", Order=0)]
        public labcoreWS.servicioPruebasLabcore.ordenesResponseBody Body;
        
        public ordenesResponse() {
        }
        
        public ordenesResponse(labcoreWS.servicioPruebasLabcore.ordenesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://husi.org/")]
    public partial class ordenesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ordenesResult;
        
        public ordenesResponseBody() {
        }
        
        public ordenesResponseBody(string ordenesResult) {
            this.ordenesResult = ordenesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitudesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitudes", Namespace="http://husi.org/", Order=0)]
        public labcoreWS.servicioPruebasLabcore.solicitudesRequestBody Body;
        
        public solicitudesRequest() {
        }
        
        public solicitudesRequest(labcoreWS.servicioPruebasLabcore.solicitudesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://husi.org/")]
    public partial class solicitudesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solicitudInput;
        
        public solicitudesRequestBody() {
        }
        
        public solicitudesRequestBody(string solicitudInput) {
            this.solicitudInput = solicitudInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitudesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitudesResponse", Namespace="http://husi.org/", Order=0)]
        public labcoreWS.servicioPruebasLabcore.solicitudesResponseBody Body;
        
        public solicitudesResponse() {
        }
        
        public solicitudesResponse(labcoreWS.servicioPruebasLabcore.solicitudesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://husi.org/")]
    public partial class solicitudesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solicitudesResult;
        
        public solicitudesResponseBody() {
        }
        
        public solicitudesResponseBody(string solicitudesResult) {
            this.solicitudesResult = solicitudesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsLabcoreSahiSoapChannel : labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLabcoreSahiSoapClient : System.ServiceModel.ClientBase<labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap>, labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap {
        
        public wsLabcoreSahiSoapClient() {
        }
        
        public wsLabcoreSahiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsLabcoreSahiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLabcoreSahiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLabcoreSahiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.servicioPruebasLabcore.ordenesResponse labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap.ordenes(labcoreWS.servicioPruebasLabcore.ordenesRequest request) {
            return base.Channel.ordenes(request);
        }
        
        public string ordenes(string ordenesInput) {
            labcoreWS.servicioPruebasLabcore.ordenesRequest inValue = new labcoreWS.servicioPruebasLabcore.ordenesRequest();
            inValue.Body = new labcoreWS.servicioPruebasLabcore.ordenesRequestBody();
            inValue.Body.ordenesInput = ordenesInput;
            labcoreWS.servicioPruebasLabcore.ordenesResponse retVal = ((labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap)(this)).ordenes(inValue);
            return retVal.Body.ordenesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.ordenesResponse> labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap.ordenesAsync(labcoreWS.servicioPruebasLabcore.ordenesRequest request) {
            return base.Channel.ordenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.ordenesResponse> ordenesAsync(string ordenesInput) {
            labcoreWS.servicioPruebasLabcore.ordenesRequest inValue = new labcoreWS.servicioPruebasLabcore.ordenesRequest();
            inValue.Body = new labcoreWS.servicioPruebasLabcore.ordenesRequestBody();
            inValue.Body.ordenesInput = ordenesInput;
            return ((labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap)(this)).ordenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        labcoreWS.servicioPruebasLabcore.solicitudesResponse labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap.solicitudes(labcoreWS.servicioPruebasLabcore.solicitudesRequest request) {
            return base.Channel.solicitudes(request);
        }
        
        public string solicitudes(string solicitudInput) {
            labcoreWS.servicioPruebasLabcore.solicitudesRequest inValue = new labcoreWS.servicioPruebasLabcore.solicitudesRequest();
            inValue.Body = new labcoreWS.servicioPruebasLabcore.solicitudesRequestBody();
            inValue.Body.solicitudInput = solicitudInput;
            labcoreWS.servicioPruebasLabcore.solicitudesResponse retVal = ((labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap)(this)).solicitudes(inValue);
            return retVal.Body.solicitudesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.solicitudesResponse> labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap.solicitudesAsync(labcoreWS.servicioPruebasLabcore.solicitudesRequest request) {
            return base.Channel.solicitudesAsync(request);
        }
        
        public System.Threading.Tasks.Task<labcoreWS.servicioPruebasLabcore.solicitudesResponse> solicitudesAsync(string solicitudInput) {
            labcoreWS.servicioPruebasLabcore.solicitudesRequest inValue = new labcoreWS.servicioPruebasLabcore.solicitudesRequest();
            inValue.Body = new labcoreWS.servicioPruebasLabcore.solicitudesRequestBody();
            inValue.Body.solicitudInput = solicitudInput;
            return ((labcoreWS.servicioPruebasLabcore.wsLabcoreSahiSoap)(this)).solicitudesAsync(inValue);
        }
    }
}
