//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.srProxyOrdenar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srProxyOrdenar.IordenarEstudio")]
    public interface IordenarEstudio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IordenarEstudio/ordenar", ReplyAction="http://tempuri.org/IordenarEstudio/ordenarResponse")]
        string ordenar(string solicitud, string orden, string atencion, int NroMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IordenarEstudio/ordenar", ReplyAction="http://tempuri.org/IordenarEstudio/ordenarResponse")]
        System.Threading.Tasks.Task<string> ordenarAsync(string solicitud, string orden, string atencion, int NroMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IordenarEstudio/cambioEstado", ReplyAction="http://tempuri.org/IordenarEstudio/cambioEstadoResponse")]
        string cambioEstado(string msgHL7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IordenarEstudio/cambioEstado", ReplyAction="http://tempuri.org/IordenarEstudio/cambioEstadoResponse")]
        System.Threading.Tasks.Task<string> cambioEstadoAsync(string msgHL7);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IordenarEstudioChannel : labcoreWS.srProxyOrdenar.IordenarEstudio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IordenarEstudioClient : System.ServiceModel.ClientBase<labcoreWS.srProxyOrdenar.IordenarEstudio>, labcoreWS.srProxyOrdenar.IordenarEstudio {
        
        public IordenarEstudioClient() {
        }
        
        public IordenarEstudioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IordenarEstudioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IordenarEstudioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IordenarEstudioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ordenar(string solicitud, string orden, string atencion, int NroMsg) {
            return base.Channel.ordenar(solicitud, orden, atencion, NroMsg);
        }
        
        public System.Threading.Tasks.Task<string> ordenarAsync(string solicitud, string orden, string atencion, int NroMsg) {
            return base.Channel.ordenarAsync(solicitud, orden, atencion, NroMsg);
        }
        
        public string cambioEstado(string msgHL7) {
            return base.Channel.cambioEstado(msgHL7);
        }
        
        public System.Threading.Tasks.Task<string> cambioEstadoAsync(string msgHL7) {
            return base.Channel.cambioEstadoAsync(msgHL7);
        }
    }
}
