//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labcoreWS.clienteDatosPcte {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pacienteS1", Namespace="http://schemas.datacontract.org/2004/07/husiWSGeneral.Modelos")]
    [System.SerializableAttribute()]
    public partial class pacienteS1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaEgresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lugarIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialEpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoatencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubicacionActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubicacionEgresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubicacionIngresoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrato {
            get {
                return this.contratoField;
            }
            set {
                if ((object.ReferenceEquals(this.contratoField, value) != true)) {
                    this.contratoField = value;
                    this.RaisePropertyChanged("contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string edad {
            get {
                return this.edadField;
            }
            set {
                if ((object.ReferenceEquals(this.edadField, value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaEgreso {
            get {
                return this.fechaEgresoField;
            }
            set {
                if ((this.fechaEgresoField.Equals(value) != true)) {
                    this.fechaEgresoField = value;
                    this.RaisePropertyChanged("fechaEgreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                if ((this.fechaIngresoField.Equals(value) != true)) {
                    this.fechaIngresoField = value;
                    this.RaisePropertyChanged("fechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAtencion {
            get {
                return this.idAtencionField;
            }
            set {
                if ((this.idAtencionField.Equals(value) != true)) {
                    this.idAtencionField = value;
                    this.RaisePropertyChanged("idAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                if ((this.idPacienteField.Equals(value) != true)) {
                    this.idPacienteField = value;
                    this.RaisePropertyChanged("idPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lugarIngreso {
            get {
                return this.lugarIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.lugarIngresoField, value) != true)) {
                    this.lugarIngresoField = value;
                    this.RaisePropertyChanged("lugarIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numDocumentoField, value) != true)) {
                    this.numDocumentoField = value;
                    this.RaisePropertyChanged("numDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocialEps {
            get {
                return this.razonSocialEpsField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialEpsField, value) != true)) {
                    this.razonSocialEpsField = value;
                    this.RaisePropertyChanged("razonSocialEps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoField, value) != true)) {
                    this.tipoDocumentoField = value;
                    this.RaisePropertyChanged("tipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoatencion {
            get {
                return this.tipoatencionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoatencionField, value) != true)) {
                    this.tipoatencionField = value;
                    this.RaisePropertyChanged("tipoatencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ubicacionActual {
            get {
                return this.ubicacionActualField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionActualField, value) != true)) {
                    this.ubicacionActualField = value;
                    this.RaisePropertyChanged("ubicacionActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ubicacionEgreso {
            get {
                return this.ubicacionEgresoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionEgresoField, value) != true)) {
                    this.ubicacionEgresoField = value;
                    this.RaisePropertyChanged("ubicacionEgreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ubicacionIngreso {
            get {
                return this.ubicacionIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionIngresoField, value) != true)) {
                    this.ubicacionIngresoField = value;
                    this.RaisePropertyChanged("ubicacionIngreso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="clienteDatosPcte.IdatosPaciente")]
    public interface IdatosPaciente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdatosPaciente/datosXatencion", ReplyAction="http://tempuri.org/IdatosPaciente/datosXatencionResponse")]
        labcoreWS.clienteDatosPcte.pacienteS1 datosXatencion(int nroAtencion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdatosPacienteChannel : labcoreWS.clienteDatosPcte.IdatosPaciente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdatosPacienteClient : System.ServiceModel.ClientBase<labcoreWS.clienteDatosPcte.IdatosPaciente>, labcoreWS.clienteDatosPcte.IdatosPaciente {
        
        public IdatosPacienteClient() {
        }
        
        public IdatosPacienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdatosPacienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdatosPacienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdatosPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public labcoreWS.clienteDatosPcte.pacienteS1 datosXatencion(int nroAtencion) {
            return base.Channel.datosXatencion(nroAtencion);
        }
    }
}
